config/routes.rb
FivV4::Application.routes.draw do
  

  devise_for :users

  resources :brands

  resources :pants do
    resources :reviews
  end
  resources :reviews

  root :to => "home#index"
  

  

end

app/models/attribute_models/pant_type.rb
class PantType < ActiveEnum::Base
  value :id => 1, 
        :name => 'Jeans'

  value :id => 2, 
        :name => 'Dress Pants'

  value :id => 3, 
        :name => 'Khaki'

  value :id => 4, 
        :name => 'Cordoroy'

  value :id => 5, 
        :name => 'Other'

end

app/models/pant.rb
class Pant < ActiveRecord::Base

  # Relationships
  belongs_to :brand
  has_many :reviews, through: :pant_instances, dependent: :destroy
  has_many :store_links
  has_many :pant_instances
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>", :full => "600x600" }

  # Nested Attributes
  accepts_nested_attributes_for :store_links,
      :reject_if => :all_blank,
      :allow_destroy => true
  
  #has_many :attachments, :as => :attachable, :dependent => :destroy
  #has_one :attachment, :as => :attachable, :dependent => :destroy

  # Validations
  validates :name, :brand_id, presence: true

  # Enums
  enumerate :rise, :with => Rise
  enumerate :leg_cut, :with => LegCut
  enumerate :body_shape, :with => BodyShape
  enumerate :pant_style, :with => PantStyle
  enumerate :pantType, :with => PantType


  def self.search(search)
    if search
      where 'name LIKE ?', "%#{search}%"
    else
      scoped
    end
  end
  
end

app/controllers/pants_controller.rb
class PantsController < ApplicationController
  before_action :set_pant, only: [:show, :edit, :update, :destroy]

  # GET /pants
  # GET /pants.json
  def index
    if params[:search]
      @pants = Pant.search(params[:search])
    else
      @pants = Pant.all
    end
  end

  # GET /pants/1
  # GET /pants/1.json
  def show
  end

  # GET /pants/new
  def new
    @pant = Pant.new
  end

  # GET /pants/1/edit
  def edit
  end

  # POST /pants
  # POST /pants.json
  def create
    @pant = Pant.new(pant_params)

    respond_to do |format|
      if @pant.save
        format.html { redirect_to @pant, notice: 'Pant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pant }
      else
        format.html { render action: 'new' }
        format.json { render json: @pant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pants/1
  # PATCH/PUT /pants/1.json
  def update
    respond_to do |format|
      if @pant.update(pant_params)
        format.html { redirect_to @pant, notice: 'Pant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pants/1
  # DELETE /pants/1.json
  def destroy
    @pant.destroy
    respond_to do |format|
      format.html { redirect_to pants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pant
      @pant = Pant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pant_params
      params.require(:pant).permit(:name, :year, :style, :price_range, :brand_id, :image,
        :body_shape, :leg_cut, :pant_type, :rise, :exact_rise, :store_links_attributes => [:id, :url, :name, :source] )
    end
end

app/helpers/pants_helper.rb
module PantsHelper
	def setup_links(pant)
    pant.store_links.build
    pant
  end
end

app/views/pants/_form.html.erb
<%= form_for(setup_links(@pant), :html => { :multipart => true }) do |f| %>
  <% if @pant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pant.errors.count, "error") %> prohibited this pant from being saved:</h2>

      <ul>
      <% @pant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brand_id %><br />
    <%= f.collection_select :brand_id, Brand.all, :id, :name,  {:include_blank => 'None'} %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
  </div>

  <div class="field">
    <%= f.label :leg_cut %><br>
    <%= f.select :leg_cut, LegCut.to_select, required: true %>
  </div>
  <div class="field">
    <%= f.label :body_shape %><br>
    <%= f.select :body_shape, BodyShape.to_select, required: true %>
  </div>

  <div class="field">
    <%= f.label :rise %><br>
    <%= f.select :rise, Rise.to_select, required: true, selected: 3 %>
    <%= f.label :exact_rise %><br>
    <%= f.text_field :exact_rise %>
  </div>
  <div class="field">
    <%= f.label :image, "Attach a File" %>
    <%= f.file_field :image %>
    <%= f.label :price_range %><br>
    <%= f.number_field :price_range %>
  </div>

  <div class="field">
    <%= content_tag :h4, 'Links to Places to purchase the pant' %>
    <%= f.fields_for :store_links, @pant.store_links do |ff| %>
      <div>
        <%= ff.label :name %>
        <%= ff.text_field :name %>
        <%= ff.label :url %>
        <%= ff.text_field :url %>
      </div>
    <% end %>


  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pants/edit.html.erb
<h1>Editing pant</h1>

<%= render 'form' %>

<%= link_to 'Show', @pant %> |
<%= link_to 'Back', pants_path %>

app/views/pants/index.html.erb
<h1>Listing pants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Style</th>
      <th>Price range</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <div class="row">
    <% @pants.each do |pant| %>
    <div class="grid-tile">
      <div class="thumbnail">
        <%= image_tag pant.image.url %>
        <div class="caption">
          <h3><%= link_to pant.name, pant %></h3>
          <p>
            <%= pant.brand.name %>
          </p>
        </div>
      </div>
    </div> <!-- /.col -->
    <% end %>
  </div> <!-- /.row -->
  <tbody>
    <% @pants.each do |pant| %>
      <tr>
        <td><%= pant.name %></td>
        <td><%= pant.year %></td>
        <td><%= pant.style %></td>
        <td><%= pant.price_range %></td>
        <td><%= link_to 'Show', pant %></td>
        <td><%= link_to 'Edit', edit_pant_path(pant) %></td>
        <td><%= link_to 'Destroy', pant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pant', new_pant_path %>

app/views/pants/new.html.erb
<h1>New pant</h1>

<%= render 'form' %>

<%= link_to 'Back', pants_path %>

app/views/pants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pant.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @pant.brand ? @pant.brand.name : ''%>
</p>

<p>
  <strong>Year:</strong>
  <%= @pant.year %>
</p>

<p>
  <strong>Style:</strong>
  <%= @pant.style %>
</p>

<p>
  <strong>Price range:</strong>
  <%= @pant.price_range %>
</p>
<%= image_tag @pant.image.url %>
<%# @pant.images.each do |image|  %>
<%#= image_tag image.url %>
<%#= image_tag image.url(:medium) %>
<%#= image_tag image.url(:thumb) %>
<%# end %>
<% if @pant.reviews.length > 0 %>
  <%= 'Has a review' %>
<% end %>

<% if @pant.store_links.length > 0 %>
  <%=  @pant.store_links.first.url %>
<% end %>




<%= link_to 'Edit', edit_pant_path(@pant) %> |
<%= link_to 'Back', pants_path %>