config/routes.rb
FivV4::Application.routes.draw do
  

  devise_for :users

  resources :brands

  resources :pants do
    resources :reviews
  end
  resources :reviews

  root :to => "home#index"
  

  

end

app/views/layouts/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/shared/_footer.html.erb
<div class="row footer">
  FOOTER  
</div>

app/views/layouts/shared/_nav.html.erb
<div class="contain-to-grid">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h1><a href="/">Your Fit</a></h1>
            </li>
             <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
                <% if user_signed_in? %>
                    <li><%= link_to('Edit account', edit_user_registration_path) %></li>
                    <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
                <% else %>
                    <li><%= link_to('Login', new_user_session_path) %></li>
                    <li><%= link_to('Sign up', new_user_registration_path) %></li>
                <% end %>
            </ul>

            <!-- Left Nav Section -->
            <ul class="left">
                <li class="has-dropdown">
                    <a href="#">Pants</a>
                    <ul class="dropdown">
                        <li><%= link_to "Show All Pants", pants_path %></li>
                        <li><%= link_to "Add New Pant", new_pant_path %></li>
                    </ul>
                </li>
                <li class="has-dropdown">
                    <a href="#">Reviews</a>
                    <ul class="dropdown">
                        <li><%= link_to "Show All Reviews", reviews_path %></li>
                        <li><%= link_to "New Reviews", new_review_path %></li>
                    </ul>
                </li>
            </ul>
        </section>
    </nav>
</div>